#if !defined LOG_IDS_H
#define LOG_IDS_H

// IMPORTANT: This file is included by .S and .c files and will be
// processed by Python scripts, so it must ONLY contain #defines!

// The binary logs generated by the umod4 system take the form of
// 8 bits of LOGID information followed by 0 or more bytes of data.
// The amount of data depends on the specific LOGID byte.
// To help humans and tools decode LOGID information, the system
// defines items to be logged using a naming convention.

// Naming Convention
//
// The system will define a set of LOGID values that each subsystem can use to emit log records.
// At the moment, there are 4 subsystems:
//    1. GEN    general subsystem, not necessarily tied to any specific subsystem
//    2. ECU    the HC11 ECU is the source of these log messages
//    3. EP     the EP is the source of these log messages
//    4. WP     the WP is the source of these log messages

// Each subsystem will include this file to find out the subspace of the LOGIDs that they can use
// within the 256-entry LOGID space. The _BASE and _LAST symbols define a subsystem's start and end offsets
// assigned to them within the LOGID space. These spaces will not overlap.

// Each log event is represented by a single macro that encodes both its unique ID and data type:
//
//    LOGID_<subsystem>_<name>_TYPE_<typeID>
//
// The macro expands to an 8‑bit value that uniquely identifies the event.
// The suffix _TYPE_* (e.g., _TYPE_U8, _TYPE_TS) is merely part of the naming convention
// and indicates what kind of data follows the ID.
// Allowable types are defined below.
//
// A matching LOGID_<subsystem>_<name>_DLEN macro must be defined to specify how many bytes of payload accompany the ID.

// The system may optionally define literal constants to help decode raw data associated with a specific LOGID.
// If present, the naming convention is chosen to make sure that literals are to be associated with specific LOGID values:
//    LOGID_<subsystem>_<name>_VAL_<constant_name>
//
// Data Types
//
// The data associated with each LOGID is typed. The type information will be encoded in the TYPE name
// by appending the various type ID strings 'XX' shown below using the general form LOGID_<subsystem>_<name>_TYPE_XX:
//
// *** WARNING:
// *** If you make changes to the naming convention, you MUST update the generate_encoder.py utility
// *** to properly generate the logEncoder data structure!!!
// ***
//
//    _I16  int16   Signed 16-bit int
//    _U16  uint16  Unsigned 16-bit int
//    _TS   uint16  A Timestamp marker.
//                  Timestamps are derived from a free-running 16-bit counter in the ECU with a precision of 2 uSec per tick.
//                  All untimestamped events in the log before this _TS event must have occurred before this time.
//                  All untimestamped events in the log after this _TS event must have occurred after this time
//                  It is the responsibility of a log decoder to properly track 16-bit rollover events
//    _PTS  uint16  A 'prescriptive' timestamp associated with an event.
//                  Prescriptive timestamps can describe events that will occur in the future (like when an injector pulse is scheduled to begin)
//                  or things in the past (like reporting the time at which a spark detect event was actually observed)
//    _I8   int8    Signed 8-bit int
//    _U8   uint8   Unsigned 8-bit int
//    _B    bool    (0 means false, and non-zero means true)
//    _xPy  fixPt   A general fixed point form where x digits in front of an assumed decimal point with y digits after it.
//                  Examples:
//                      LOGID_ECU_FOO_TYPE_0P8  would represent an 8-bit 0.8 fixed point value
//                      LOGID_ECU_FOO_TYPE_4P12 would represent a 16-bit 4.12 fixed point value
//    _V    void    Indicates that the log entry carries no useful data
//                  NOTE: if _DLEN > 0, DLEN bytes will exist in the log data but must be discarded by the decoder
//    _CS   char    Next character of a C-string
//                  The string can be considered complete when this character has the value NULL (0x00).
//                  Note: Turning _CS characters into a string implies stateful processing by a decoder:
//                      The first _CS LOGID observed will initialize a string buffer and store the first character in it.
//                      Subsequent _CS LOGIDs will append the new character to the existing string buffer.
//                      When a _CS LOGID is observed with a NULL character, the string is complete for decoding purposes.
//
// A complete example of the naming convention follows.
//
// Definition of symbols:
//     Assume that the ECU wants to log that it is performing an unexpected CPU event, specifically, an RTI event.
//
// #define LOGID_ECU_CPU_EVENT_TYPE_U8      ((LOGID_ECU_BASE) + 0x00)   // Assign this log event its own ID value relative to the start of the ECU subspace
// #define LOGID_ECU_CPU_EVENT_DLEN         1                           // Type U8 indicates that a single byte will follow the LOGID_ECU_CPU_EVENT_TYPE_U8 byte in the log
// Value constants for LOGID_ECU_CPU_EVENT_TYPE_U8:
// #define     LOGID_ECU_CPU_EVENT_VAL_RTI             (0x0)
// #define     LOGID_ECU_CPU_EVENT_VAL_IRQ             (0x1)

// Usage of symbols (using HC11 assembly language as an example)
//      ldaA    #LOGID_ECU_CPU_EVENT_VAL_RTI        ; LOGID_ECU_CPU_EVENT_TYPE_U8 will fit in an 8-bit register
//      staA    LW + LOGID_ECU_CPU_EVENT_TYPE_U8



// We start by defining how the 256 bytes of the LOGID space gets split among
// among the subsystems: GEN (general use), ECU, EP, and WP.

// The first 0x10 locations from [0x00..0x0F] are reserved for general information.
#define     LOGID_GEN_BASE                          (0x00)
#define     LOGID_GEN_LAST                          (0x0F)

// The ECU is by far the biggest source of log events.
// Define the range of IDs assigned to the ECU data stream:
#define     LOGID_ECU_BASE                          (0x10)
#define     LOGID_ECU_LAST                          (0xCF)

// Define the range of IDs assigned to the EP:
#define     LOGID_EP_BASE                           (0xD0)
#define     LOGID_EP_LAST                           (0xDF)

// Define the range of IDs assigned to the WP:
#define     LOGID_WP_BASE                           (0xE0)
#define     LOGID_WP_LAST                           (0xFF)


// ====================================================================================================
// Define the LOGID space reserved for general information by ECU, EP, and WP subsystems.

// Defining a zero byte as being usused with no data lets us skip a sequence of zero bytes, should that prove useful
#define     LOGID_GEN_UNUSED_V                      ((LOGID_GEN_BASE) + 0x00)
#define     LOGID_GEN_UNUSED_DLEN                   0

// Logging version numbers that the logging subsystems will be using are part of the
// general subsystem, not the specific subsystems. In theory, this would allow
// the subsystems to even change their base addresses because that could be baked
// into their version numbers.
#define     LOGID_GEN_ECU_LOG_VER_TYPE_U8           ((LOGID_GEN_BASE) + 0x01)
#define     LOGID_GEN_ECU_LOG_VER_DLEN              1

#define     LOGID_GEN_EP_LOG_VER_TYPE_U8            ((LOGID_GEN_BASE) + 0x02)
#define     LOGID_GEN_EP_LOG_VER_DLEN               1

#define     LOGID_GEN_WP_LOG_VER_TYPE_U8            ((LOGID_GEN_BASE) + 0x03)
#define     LOGID_GEN_WP_LOG_VER_DLEN               1

// ====================================================================================================
// Define the LOGID space reserved for the ECU.
//
// As of ultraMod4, the logging hardware is capable of capturing every single
// write cycle showing up at the EPROM, even if writes occur on adjacent bus
// cycles as occurs with STD instructions that write 16 bits of data
// as two successive writes. For example, a STD to address X would write:
//    addr X+0: contents of A (high byte)
//    addr X+1: contents of B (low byte)
//
// To write a single 8-bit value, use STA or STB to the proper log address.
//

// The LOG_VER refers to the version of this ECU-specific header file.
#define     LOGID_GEN_ECU_LOG_VER_VAL_V0            (0x00)      // Value constant for LOGID_GEN_ECU_LOG_VER_U8

// Except for RESET, all of these events represent bad things going on inside the CPU.
// They mainly represent situations where interrupts handlers got invoked
// which were never expected to be invoked.
#define   LOGID_ECU_CPU_EVENT_TYPE_U8               ((LOGID_ECU_BASE) + 0x00)
#define   LOGID_ECU_CPU_EVENT_DLEN                  1
// Value constants for LOGID_ECU_CPU_EVENT_TYPE_U8:
#define     LOGID_ECU_CPU_EVENT_VAL_RTI             (0x0)
#define     LOGID_ECU_CPU_EVENT_VAL_IRQ             (0x1)
#define     LOGID_ECU_CPU_EVENT_VAL_XIRQ            (0x2)
#define     LOGID_ECU_CPU_EVENT_VAL_SWI             (0x3)
#define     LOGID_ECU_CPU_EVENT_VAL_IOP             (0x4)
#define     LOGID_ECU_CPU_EVENT_VAL_COP             (0x5)
#define     LOGID_ECU_CPU_EVENT_VAL_CMF             (0x6)
#define     LOGID_ECU_CPU_EVENT_VAL_RESET           (0x7)
#define     LOGID_ECU_CPU_EVENT_VAL_OC5F            (0x8)
#define     LOGID_ECU_CPU_EVENT_VAL_OC4F            (0x9)
#define     LOGID_ECU_CPU_EVENT_VAL_OC3F            (0xA)
#define     LOGID_ECU_CPU_EVENT_VAL_IC3             (0xB)

#define   LOGID_ECU_METADATA_TYPE_CS                ((LOGID_ECU_BASE) + 0x01)       // The build metadata string
#define   LOGID_ECU_METADATA_DLEN                   1

#define   LOGID_ECU_T1_OFLO_TYPE_TS                 ((LOGID_ECU_BASE) + 0x02)       // Emitted just after time T1 overflows (every 131072 uSec, or ~7.6Hz )
#define   LOGID_ECU_T1_OFLO_DLEN                    2

#define   LOGID_ECU_L4000_EVENT_TYPE_U8             ((LOGID_ECU_BASE) + 0x08)
#define   LOGID_ECU_L4000_EVENT_DLEN                1

#define   LOGID_ECU_T1_HOFLO_TYPE_TS                ((LOGID_ECU_BASE) + 0x0E)       // Marks when the ECU has observed a 'half overflow',
#define   LOGID_ECU_T1_HOFLO_TYPE_DLEN              2                               // meaning the timer has advanced into the upper 15 bits of the timer count


// Injector events, front and rear
#define   LOGID_ECU_F_INJ_ON_TYPE_PTS               ((LOGID_ECU_BASE) + 0x10)       // timestamp of injector on time in ticks
#define   LOGID_ECU_F_INJ_ON_DLEN                   2

#define   LOGID_ECU_F_INJ_DUR_TYPE_U16              ((LOGID_ECU_BASE) + 0x12)       // duration of injector pulse in ticks
#define   LOGID_ECU_F_INJ_DUR_DLEN                  2

#define   LOGID_ECU_R_INJ_ON_TYPE_PTS               ((LOGID_ECU_BASE) + 0x14)       // timestamp of injector on time in ticks
#define   LOGID_ECU_R_INJ_ON_DLEN                   2

#define   LOGID_ECU_R_INJ_DUR_TYPE_U16              ((LOGID_ECU_BASE) + 0x16)       // duration of injector pulse in ticks
#define   LOGID_ECU_R_INJ_DUR_DLEN                  2

// Ignition coil events, front and rear
#define   LOGID_ECU_F_COIL_ON_TYPE_PTS              ((LOGID_ECU_BASE) + 0x20)
#define   LOGID_ECU_F_COIL_ON_DLEN                  2

#define   LOGID_ECU_F_COIL_OFF_TYPE_PTS             ((LOGID_ECU_BASE) + 0x22)
#define   LOGID_ECU_F_COIL_OFF_DLEN                 2

#define   LOGID_ECU_R_COIL_ON_TYPE_PTS              ((LOGID_ECU_BASE) + 0x24)
#define   LOGID_ECU_R_COIL_ON_DLEN                  2

#define   LOGID_ECU_R_COIL_OFF_TYPE_PTS             ((LOGID_ECU_BASE) + 0x26)
#define   LOGID_ECU_R_COIL_OFF_DLEN                 2

#define   LOGID_ECU_F_COIL_MAN_ON_TYPE_PTS          ((LOGID_ECU_BASE) + 0x28)
#define   LOGID_ECU_F_COIL_MAN_ON_DLEN              2

#define   LOGID_ECU_F_COIL_MAN_OFF_TYPE_PTS         ((LOGID_ECU_BASE) + 0x2A)
#define   LOGID_ECU_F_COIL_MAN_OFF_DLEN             2

#define   LOGID_ECU_R_COIL_MAN_ON_TYPE_PTS          ((LOGID_ECU_BASE) + 0x2C)
#define   LOGID_ECU_R_COIL_MAN_ON_DLEN              2

#define   LOGID_ECU_R_COIL_MAN_OFF_TYPE_PTS         ((LOGID_ECU_BASE) + 0x2E)
#define   LOGID_ECU_R_COIL_MAN_OFF_DLEN             2

#define   LOGID_ECU_F_IGN_DLY_TYPE_0P8              ((LOGID_ECU_BASE) + 0x30)           // 0.8 fraction of 90 degrees (the value of L00DC during CR3)
#define   LOGID_ECU_F_IGN_DLY_DLEN                  1

#define   LOGID_ECU_R_IGN_DLY_TYPE_0P8              ((LOGID_ECU_BASE) + 0x32)           // 0.8 fraction of 90 degrees (the value of L00DF during CR8)
#define   LOGID_ECU_R_IGN_DLY_DLEN                  1

// Here are various other ungrouped events:
#define   LOGID_ECU_5MILLISEC_EVENT_TYPE_V          ((LOGID_ECU_BASE) + 0x38)           // indicates every time the 5 msec routine runs
#define   LOGID_ECU_5MILLISEC_EVENT_DLEN            1                                   // ignore this garbage byte

#define   LOGID_ECU_CRANK_P6_MAX_TYPE_V             ((LOGID_ECU_BASE) + 0x39)           // this indicates that the rotational period of the crank was too slow to track
#define   LOGID_ECU_CRANK_P6_MAX_DLEN               1                                   // ignore this garbage byte

#define   LOGID_ECU_FUEL_PUMP_TYPE_B                ((LOGID_ECU_BASE) + 0x3A)           // boolean represents the state of the fuel pump drive: false means pump off, true means pump on
#define   LOGID_ECU_FUEL_PUMP_DLEN                  1

#define   LOGID_ECU_ECU_ERROR_L000C_TYPE_U8         ((LOGID_ECU_BASE) + 0x40)           // the 8 error bits stored in L000C
#define   LOGID_ECU_ECU_ERROR_L000C_DLEN            1

#define   LOGID_ECU_ECU_ERROR_L000D_TYPE_U8         ((LOGID_ECU_BASE) + 0x41)           // the 8 error bits stored in L000D
#define   LOGID_ECU_ECU_ERROR_L000D_DLEN            1

#define   LOGID_ECU_ECU_ERROR_L000E_TYPE_U8         ((LOGID_ECU_BASE) + 0x42)           // the 8 error bits stored in L000E
#define   LOGID_ECU_ECU_ERROR_L000E_DLEN            1

#define   LOGID_ECU_ECU_ERROR_L000F_TYPE_U8         ((LOGID_ECU_BASE) + 0x43)           // the 8 error bits stored in L000F
#define   LOGID_ECU_ECU_ERROR_L000F_DLEN            1

#define   LOGID_ECU_TP_CO1_RAW_TYPE_U8              ((LOGID_ECU_BASE) + 0x44)           // Trim Pot CO1 raw ADC value
#define   LOGID_ECU_TP_CO1_RAW_DLEN                 1

#define   LOGID_ECU_TP_CO2_RAW_TYPE_U8              ((LOGID_ECU_BASE) + 0x45)           // Trim Pot CO2 raw ADC value
#define   LOGID_ECU_TP_CO2_RAW_DLEN                 1

#define   LOGID_ECU_TP_CO1_DB_TYPE_U8               ((LOGID_ECU_BASE) + 0x46)           // Trim Pot CO1 ADC value after deadband processing
#define   LOGID_ECU_TP_CO1_DB_DLEN                  1

#define   LOGID_ECU_TP_CO2_DB_TYPE_U8               ((LOGID_ECU_BASE) + 0x47)           // Trim Pot CO2 ADC value after deadband processing
#define   LOGID_ECU_TP_CO2_DB_DLEN                  1

#define   LOGID_ECU_TP_RPM_FACTOR_TYPE_U8           ((LOGID_ECU_BASE) + 0x48)           // RPM factor for trimp pot calculations
#define   LOGID_ECU_TP_RPM_FACTOR_DLEN              1

#define   LOGID_ECU_TP_CO1_ADJ_FACTOR_TYPE_U8       ((LOGID_ECU_BASE) + 0x49)           // Fuel trim adjustment factor from trim pot CO1
#define   LOGID_ECU_TP_CO1_ADJ_FACTOR_DLEN          1

#define   LOGID_ECU_TP_CO2_ADJ_FACTOR_TYPE_U8       ((LOGID_ECU_BASE) + 0x4A)           // Fuel trim adjustment factor from trim pot CO2
#define   LOGID_ECU_TP_CO2_ADJ_FACTOR_DLEN          1


#define   LOGID_ECU_RAW_VTA_TYPE_U16                ((LOGID_ECU_BASE) + 0x50)           // Throttle angle
#define   LOGID_ECU_RAW_VTA_DLEN                    2

#define   LOGID_ECU_RAW_MAP_TYPE_U8                 ((LOGID_ECU_BASE) + 0x52)           // Manifold air pressure
#define   LOGID_ECU_RAW_MAP_DLEN                    1

#define   LOGID_ECU_RAW_AAP_TYPE_U8                 ((LOGID_ECU_BASE) + 0x53)           // Ambient air pressure
#define   LOGID_ECU_RAW_AAP_DLEN                    1

#define   LOGID_ECU_RAW_THW_TYPE_U8                 ((LOGID_ECU_BASE) + 0x54)           // Coolant Temp
#define   LOGID_ECU_RAW_THW_DLEN                    1

#define   LOGID_ECU_RAW_THA_TYPE_U8                 ((LOGID_ECU_BASE) + 0x55)           // Air Temp
#define   LOGID_ECU_RAW_THA_DLEN                    1

#define   LOGID_ECU_RAW_VM_TYPE_U8                  ((LOGID_ECU_BASE) + 0x56)           // Voltage Monitor
#define   LOGID_ECU_RAW_VM_DLEN                     1

#define   LOGID_ECU_PORTG_DB_TYPE_U8                ((LOGID_ECU_BASE) + 0x57)           // the state of PORTG (debounced)
#define   LOGID_ECU_PORTG_DB_DLEN                   1

#define   LOGID_ECU_CRANKREF_START_TYPE_TS          ((LOGID_ECU_BASE) + 0x60)           // Timestamp of the start of the most recent crankshaft sub-rotation (6 crankrefs per full crank rotation)
#define   LOGID_ECU_CRANKREF_START_DLEN             2

#define   LOGID_ECU_CRANKREF_ID_TYPE_U8             ((LOGID_ECU_BASE) + 0x62)           // The ID of the specific crankshaft subroutation (0..11): 2 full rotations == all 4 strokes of the 4-stroke engine
#define   LOGID_ECU_CRANKREF_ID_DLEN                1

#define   LOGID_ECU_CAM_ERR_TYPE_U8                 ((LOGID_ECU_BASE) + 0x63)           // Error while processing CAM ISR
#define   LOGID_ECU_CAM_ERR_DLEN                    1

#define   LOGID_ECU_CAMSHAFT_TYPE_TS                ((LOGID_ECU_BASE) + 0x64)           // Timestamp of most recent camshaft sensor falling-edge event
#define   LOGID_ECU_CAMSHAFT_DLEN                   2

#define   LOGID_ECU_SPRK_X1_TYPE_PTS                ((LOGID_ECU_BASE) + 0x70)           // The time when front OR rear coil #1 fired
#define   LOGID_ECU_SPRK_X1_DLEN                    2                                   // By design, this is reported during the CR period AFTER it occurred

#define   LOGID_ECU_SPRK_X2_TYPE_PTS                ((LOGID_ECU_BASE) + 0x72)           // The time when front OR rear coil #2 fired
#define   LOGID_ECU_SPRK_X2_DLEN                    2                                   // By design, this is reported during the CR period AFTER it occurred

#define   LOGID_ECU_NOSPARK_TYPE_U8                 ((LOGID_ECU_BASE) + 0x74)           // U8 value indicates the coil that did not spark: 0x11, 0x12, 0x21, 0x22
#define   LOGID_ECU_NOSPARK_DLEN                    1

// ====================================================================================================
// Define the LOGID space reserved for the EP.
//
// For the moment:
// In keeping with always writing ECU data in 2-byte chunks (log ID then data),
// the multi-byte EPROM log data will be written as logID, then data.
// The same log ID will be written in front of each data byte.
// Example: writing a 4-byte EPROM M3 with a value of 0x11223344 would get sent as:
//    LOGID_EP_LOAD_M3, 0x44
//    LOGID_EP_LOAD_M3, 0x33
//    LOGID_EP_LOAD_M3, 0x22
//    LOGID_EP_LOAD_M3, 0x11

#define     LOGID_GEN_EP_LOG_VER_VAL_V0                 (0x00)                          // Version 0

#define LOGID_EP_LOAD_NAME_TYPE_CS                      ((LOGID_EP_BASE) + 0x00)        // The name of the EPROM to be loaded, written as sequence of UTF-8 chars, NULL terminated
#define LOGID_EP_LOAD_NAME_DLEN                         1

#define LOGID_EP_FIND_NAME_TYPE_CS                      ((LOGID_EP_BASE) + 0x01)        // The name of the EPROM to be found in the BSON library doc, written as sequence of UTF-8 chars, NULL terminated
#define LOGID_EP_FIND_NAME_DLEN                         1

#define LOGID_EP_LOAD_ADDR_TYPE_U16                     ((LOGID_EP_BASE) + 0x02)        // 2 bytes, LSB first
#define LOGID_EP_LOAD_ADDR_DLEN                         2

#define LOGID_EP_LOAD_LEN_TYPE_U16                      ((LOGID_EP_BASE) + 0x04)        // 4 bytes, 2-byte start addr LSB first, then length (LSB first)
#define LOGID_EP_LOAD_LEN_DLEN                          2

#define LOGID_EP_LOAD_ERR_TYPE_U8                       ((LOGID_EP_BASE) + 0x06)        // The error status byte of the most recent load operation
#define LOGID_EP_LOAD_ERR_DLEN                          1
#define     LOGID_EP_LOAD_ERR_VAL_NOERR                 0x00                            //   * no error: the load succeeded
#define     LOGID_EP_LOAD_ERR_VAL_NOTFOUND              0x01                            //   * The specified image name was not found in the BSON lib
#define     LOGID_EP_LOAD_ERR_VAL_NONAME                0x02                            //   * BSON EPROM object does not contain a name key
#define     LOGID_EP_LOAD_ERR_VAL_CKSUMERR              0x03                            //   * BSON memory contents verification failure
#define     LOGID_EP_LOAD_ERR_VAL_VERIFYERR             0x04                            //   * Verification failure after being copied to RAM
#define     LOGID_EP_LOAD_ERR_VAL_BADOFFSET             0x05                            //   * start offset is outside of EPROM size
#define     LOGID_EP_LOAD_ERR_VAL_BADLENGTH             0x06                            //   * the desired start offset plus length goes beyond end of EPROM
#define     LOGID_EP_LOAD_ERR_VAL_NODAUGHTERBOARDKEY    0x07                            //   * BSON doc is missing a DAUGHTERBOARD key
#define     LOGID_EP_LOAD_ERR_VAL_NOMEMKEY              0x08                            //   * BSON doc is missing a MEM key
#define     LOGID_EP_LOAD_ERR_VAL_M3FAIL                0x09                            //   * M3 checksum does not match the binary data
#define     LOGID_EP_LOAD_ERR_VAL_MISSINGKEYSTART       0x0A                            //   * mem object is missing its 'start' key
#define     LOGID_EP_LOAD_ERR_VAL_MISSINGKEYLENGTH      0x0B                            //   * mem object is missing its 'length' key
#define     LOGID_EP_LOAD_ERR_VAL_MISSINGKEYM3          0x0C                            //   * mem object is missing its 'm3' key
#define     LOGID_EP_LOAD_ERR_VAL_BADM3BSONTYPE         0x0D                            //   * m3 key has invalid data type (should be int32 or int64)
#define     LOGID_EP_LOAD_ERR_VAL_BADM3VALUE            0x0E                            //   * int64 m3 values should only contain 32 bits of data
#define     LOGID_EP_LOAD_ERR_VAL_NOBINKEY              0x0F                            //   * mem object is missing its 'bin' key: no binary data present
#define     LOGID_EP_LOAD_ERR_VAL_BADBINLENGTH          0x10                            //   * bin object must be exactly 32768 bytes
#define     LOGID_EP_LOAD_ERR_VAL_BADBINSUBTYPE         0x11                            //   * bin object has invalid BSON subtype

#define     LOGID_EP_LOAD_ERR_VAL_BADMAGIC              0x20                            //   * Bad Magic number in the image_store
#define     LOGID_EP_LOAD_ERR_VAL_NOIMAGES              0x21                            //   * No images found in the image_store
#define     LOGID_EP_LOAD_ERR_VAL_SELECTORIZETOOBIG     0x22                            //   * The image selector structure is too big to fit in slot 0
#define     LOGID_EP_LOAD_ERR_VAL_BAD_SLOT              0x23                            //   * The image selector structure contains an invalid slot number, must be [1..255]
#define     LOGID_EP_LOAD_ERR_VAL_BAD_HASH              0x24                            //   * The hash in the image selector did not match the data in the slot
#define     LOGID_EP_LOAD_ERR_VAL_LIMP_MODE             0x25                            //   * The EP is in limp mode, unable to load any other images

#define LOGID_EP_LOAD_IMAGESLOT_TYPE_U8                 ((LOGID_EP_BASE) + 0x07)        // Report the image slot number that we are loading (max is 255, slot 0 reserved for built-in fallback image)
#define LOGID_EP_LOAD_IMAGESLOT_DLEN                    1

#define LOGID_EP_INFO_TYPE_CS                           ((LOGID_EP_BASE) + 0x08)        // Generic informational string, NULL terminated. Content is self-describing (e.g. "dsc: user text")
#define LOGID_EP_INFO_DLEN                              1


#define LOGID_EP_LOAD_RP58MAPBLOB_TYPE_U16              ((LOGID_EP_BASE) + 0x0A)        // The EPROM load map blob, written as a sequence of 2-byte values, LSB first.
#define LOGID_EP_LOAD_RP58MAPBLOB_DLEN                  2                               // The number of elements written to the log will be (RP58_MAPBLOB_LENGTH)/2

#define LOGID_EP_IMGSEL_TYPE_CS                         ((LOGID_EP_BASE) + 0x0C)        // Per-image load results as a compact JSON array string, NULL-terminated char stream.
#define LOGID_EP_IMGSEL_DLEN                            1                               // Sent once after the loading pass completes (success or failsafe).


// ====================================================================================================
// Define the LOGID space reserved for the WP.
#define LOGID_GEN_WP_LOG_VER_VAL_V0                     (0x00)                          // Version 0

#define LOGID_WP_CSECS_TYPE_U8                          ((LOGID_WP_BASE) + 0x01)
#define LOGID_WP_CSECS_DLEN                             1

#define LOGID_WP_SECS_TYPE_U8                           ((LOGID_WP_BASE) + 0x02)
#define LOGID_WP_SECS_DLEN                              1

#define LOGID_WP_MINS_TYPE_U8                           ((LOGID_WP_BASE) + 0x03)
#define LOGID_WP_MINS_DLEN                              1

#define LOGID_WP_HOURS_TYPE_U8                          ((LOGID_WP_BASE) + 0x04)
#define LOGID_WP_HOURS_DLEN                             1

#define LOGID_WP_DATE_TYPE_U8                           ((LOGID_WP_BASE) + 0x05)
#define LOGID_WP_DATE_DLEN                              1

#define LOGID_WP_MONTH_TYPE_U8                          ((LOGID_WP_BASE) + 0x06)
#define LOGID_WP_MONTH_DLEN                             1

#define LOGID_WP_YEAR_TYPE_U8                           ((LOGID_WP_BASE) + 0x07)
#define LOGID_WP_YEAR_DLEN                              1

#define LOGID_WP_FIXTYPE_TYPE_U8                        ((LOGID_WP_BASE) + 0x08)
#define LOGID_WP_FIXTYPE_DLEN                           1

// Position is stored together as lat/long
#define LOGID_WP_GPS_POSN_TYPE_8B                       ((LOGID_WP_BASE) + 0x09)
#define LOGID_WP_GPS_POSN_DLEN                          (4+4)

// Velocity is stored separate to make it easier to graph by itself
#define LOGID_WP_GPS_VELO_TYPE_U16                      ((LOGID_WP_BASE) + 0x0A)
#define LOGID_WP_GPS_VELO_DLEN                          2

// Mark the fact that we saw a PPS event
#define LOGID_WP_GPS_PPS_TYPE_V                         ((LOGID_WP_BASE) + 0x0B)
#define LOGID_WP_GPS_PPS_DLEN                           0

// Log filesystem IO operations.
// Time will be stored as 2 bytes representing milliseconds.
// Times >= 65535 mSec will be clamped to 65535 mSec, or just over a minute.
//
// It is not required to log every filesystem operation, but it might be useful to track the max times.
#define LOGID_WP_WR_TIME_TYPE_U16                       ((LOGID_WP_BASE) + 0x0C)
#define LOGID_WP_WR_TIME_DLEN                           2
#define LOGID_WP_SYNC_TIME_TYPE_U16                     ((LOGID_WP_BASE) + 0x0D)
#define LOGID_WP_SYNC_TIME_DLEN                         2

#endif
