#if !defined LOG_BASE_H
#define LOG_BASE_H

// The filesystem logs generated by the umod4 system take the form of 
// 8 bits of ID information followed by at least 1 byte of data.
// The amount of data is dependent on the specific ID byte.
//
// This file defines how the 256 bytes of the logging ID space gets split
// among the ECU, EP, and WP.

// The first 0x10 locations from [0x00..0x0F] are reserved for global kinds of information
#define     LOGID_BASE                              (0x00)
#define     LOGID_ECU_LOG_VER_U8                    ((LOGID_BASE) + 0x01)
#define     LOGID_EP_LOG_VER_U8                     ((LOGID_BASE) + 0x02)
#define     LOGID_WP_LOG_VER_U8                     ((LOGID_BASE) + 0x03)

// Define the range of IDs assigned to the ECU data stream as [0x10..0xCF]:
#define     LOGID_ECU_BASE                          (0x10)
#define     LOGID_ECU_LAST                          (0xCF)

// Define the range of IDs assigned to the EP as [0xD0..0xDF]:
#define     LOGID_EP_BASE                           (0xD0)
#define     LOGID_EP_LAST                           (0xFF)

// Define the range of IDs assigned to the WP as [0xE0..0xFF]:
#define     LOGID_WP_BASE                           (0xE0)
#define     LOGID_WP_LAST                           (0xFF)

#endif
