#!/usr/bin/env python3
"""
bin2c.py - Convert binary file to C array

Usage: bin2c.py <input.bin> <output_base_name> <array_name> <entry_point> <stack_pointer>

Generates:
  - output_base_name.h: Header with extern declarations
  - output_base_name.c: Implementation with 32-bit word array

Example:
  bin2c.py SwdReflash.bin swdreflash_binary swdreflash 0x20000101 0x20042000
"""

import sys
import os

def bin2c(input_file, output_base, array_name, entry_point, stack_pointer):
    """Convert binary file to C source and header files."""

    # Read binary data
    with open(input_file, 'rb') as f:
        data = f.read()

    size = len(data)

    # Pad to 4-byte boundary if needed
    if size % 4 != 0:
        padding = 4 - (size % 4)
        data += b'\x00' * padding
        print(f"Warning: Padded binary from {size} to {size + padding} bytes (4-byte alignment)")

    # Convert to 32-bit words (little-endian)
    word_count = len(data) // 4
    words = []
    for i in range(0, len(data), 4):
        word = int.from_bytes(data[i:i+4], byteorder='little')
        words.append(word)

    # Generate header file
    header_file = f"{output_base}.h"
    with open(header_file, 'w') as f:
        guard = f"{array_name.upper()}_H"
        f.write(f"""/* Auto-generated from {os.path.basename(input_file)} */
/* DO NOT EDIT - Generated by bin2c.py */

#ifndef {guard}
#define {guard}

#include <stdint.h>
#include <stddef.h>

/* SwdReflash binary data (32-bit words) */
extern const uint32_t {array_name}_data[];
extern const size_t {array_name}_size;        /* Size in bytes */
extern const size_t {array_name}_word_count;  /* Number of 32-bit words */

/* Memory layout for RAM execution */
extern const uint32_t {array_name}_entry_point;  /* PC value (Thumb mode) */
extern const uint32_t {array_name}_stack_pointer; /* SP value */

#endif /* {guard} */
""")

    # Generate source file
    source_file = f"{output_base}.c"
    with open(source_file, 'w') as f:
        f.write(f"""/* Auto-generated from {os.path.basename(input_file)} */
/* DO NOT EDIT - Generated by bin2c.py */

#include "{os.path.basename(header_file)}"

/* Binary data array ({size} bytes = {word_count} words) */
const uint32_t {array_name}_data[] = {{
""")

        # Write data in rows of 4 words (16 bytes per line)
        for i in range(0, word_count, 4):
            chunk = words[i:i+4]
            hex_words = ', '.join(f'0x{w:08x}' for w in chunk)
            f.write(f"    {hex_words},\n")

        f.write(f"""}};\n
const size_t {array_name}_size = {size};
const size_t {array_name}_word_count = {word_count};

/* Memory layout for RAM execution */
const uint32_t {array_name}_entry_point = {entry_point};  /* PC (Thumb mode) */
const uint32_t {array_name}_stack_pointer = {stack_pointer}; /* SP */
""")

    print(f"Generated {header_file} and {source_file}")
    print(f"Binary size: {size} bytes ({word_count} words)")
    print(f"Entry point: {entry_point}")
    print(f"Stack pointer: {stack_pointer}")

if __name__ == '__main__':
    if len(sys.argv) != 6:
        print(__doc__)
        sys.exit(1)

    input_file = sys.argv[1]
    output_base = sys.argv[2]
    array_name = sys.argv[3]
    entry_point = sys.argv[4]
    stack_pointer = sys.argv[5]

    bin2c(input_file, output_base, array_name, entry_point, stack_pointer)
