#!/usr/bin/env python3
"""
gen_logmeta.py — Generate LogMeta.py from log_ids.h metadata macros.

Parses log_ids.h looking for _NAME and _UNITS macros alongside LOGID definitions,
resolves their numeric IDs by evaluating the C #define arithmetic, and emits
a Python module containing LOG_ID_META: a dict mapping int log ID → (name, units).

Usage:
    gen_logmeta.py <log_ids.h> -o <LogMeta.py>
"""

import re
import sys
import argparse
from pathlib import Path


def parse_defines(header_text):
    """Return a dict of all #define NAME VALUE pairs from a C header.
    Values are kept as strings for deferred evaluation."""
    defines = {}
    for line in header_text.splitlines():
        line = line.strip()
        # Strip single-line C++ and C comments after the value
        line = re.sub(r'\s*//.*$', '', line)
        line = re.sub(r'\s*/\*.*?\*/', '', line)
        m = re.match(r'^#define\s+(\w+)\s+(.*)', line)
        if m:
            name, value = m.group(1), m.group(2).strip()
            defines[name] = value
    return defines


def evaluate_define(value_str, defines, _cache=None):
    """Evaluate a C #define value expression to an integer.
    Supports simple arithmetic and nested #define references."""
    if _cache is None:
        _cache = {}

    value_str = value_str.strip()

    # Remove outer parentheses iteratively
    while value_str.startswith('(') and value_str.endswith(')'):
        inner = value_str[1:-1].strip()
        # Make sure the parens are balanced
        depth = 0
        for ch in inner:
            if ch == '(':
                depth += 1
            elif ch == ')':
                depth -= 1
            if depth < 0:
                break
        else:
            value_str = inner
            continue
        break

    # Try literal hex
    if re.fullmatch(r'0[xX][0-9A-Fa-f]+', value_str):
        return int(value_str, 16)

    # Try literal decimal
    if re.fullmatch(r'-?\d+', value_str):
        return int(value_str)

    # Try known define name
    if re.fullmatch(r'\w+', value_str):
        if value_str in _cache:
            return _cache[value_str]
        if value_str in defines:
            result = evaluate_define(defines[value_str], defines, _cache)
            _cache[value_str] = result
            return result
        return None

    # Try simple binary expression: A + B or A - B
    # Split on the last + or - that is not inside parentheses
    for op in ('+', '-'):
        depth = 0
        for i in range(len(value_str) - 1, -1, -1):
            ch = value_str[i]
            if ch == ')':
                depth += 1
            elif ch == '(':
                depth -= 1
            elif ch == op and depth == 0 and i > 0:
                left = evaluate_define(value_str[:i], defines, _cache)
                right = evaluate_define(value_str[i+1:], defines, _cache)
                if left is not None and right is not None:
                    return left + right if op == '+' else left - right

    return None


def unquote(s):
    """Strip surrounding double-quotes from a C string literal."""
    s = s.strip()
    if s.startswith('"') and s.endswith('"'):
        return s[1:-1]
    return s


def main():
    parser = argparse.ArgumentParser(description='Generate LogMeta.py from log_ids.h')
    parser.add_argument('header', help='Path to log_ids.h')
    parser.add_argument('-o', '--output', required=True, help='Output LogMeta.py path')
    args = parser.parse_args()

    header_text = Path(args.header).read_text(encoding='utf-8')
    defines = parse_defines(header_text)

    # Resolve all LOGID_*_TYPE_* symbols to numeric IDs
    id_values = {}   # symbol_base → int  (e.g. 'LOGID_ECU_RAW_VM' → 0x66)
    for name, value in defines.items():
        m = re.match(r'^(LOGID_\w+)_TYPE_\w+$', name)
        if m:
            base = m.group(1)
            num = evaluate_define(value, defines)
            if num is not None:
                id_values[base] = num

    # Collect _NAME/_UNITS macros
    names = {}    # symbol_base → str
    units = {}    # symbol_base → str
    for name, value in defines.items():
        m = re.match(r'^(LOGID_\w+)_NAME$', name)
        if m:
            names[m.group(1)] = unquote(value)
        m = re.match(r'^(LOGID_\w+)_UNITS$', name)
        if m:
            units[m.group(1)] = unquote(value)

    # Build the output dict: only entries that have both a numeric ID and _NAME
    meta = {}   # int → (name_str, units_str)
    for base, num in sorted(id_values.items(), key=lambda x: x[1]):
        if base in names:
            unit_str = units.get(base, '')
            if 0 <= num <= 255:
                meta[num] = (names[base], unit_str)

    # Emit LogMeta.py
    out_lines = [
        '# Auto-generated by gen_logmeta.py — do not edit.',
        '# Source: log_ids.h  (run cmake to regenerate)',
        '',
        'LOG_ID_META = {',
    ]
    for num, (name, unit) in sorted(meta.items()):
        out_lines.append('    0x{:02X}: ({!r}, {!r}),'.format(num, name, unit))
    out_lines += ['}', '']

    Path(args.output).write_text('\n'.join(out_lines), encoding='utf-8')
    print('gen_logmeta: wrote {} entries to {}'.format(len(meta), args.output))


if __name__ == '__main__':
    main()
