### Do Not Edit - Automatically Generated via:
###
###     tools/src/h2py.py ecu/src/ECU_log.h EP/src/EP_log.h WP/src/WP_log.h -o tools/src/logsyms.py --module-level
###

# Module-level constants extracted from C header files

LOGID_GEN_ECU_LOG_VER_VAL_V0 = (0x00)                                          # 0
LOGID_ECU_CPU_EVENT_TYPE_U8 = ((LOGID_ECU_BASE) + 0x00)                        # ((LOGID_ECU_BASE) + 0x00)
LOGID_ECU_CPU_EVENT_DLEN = 1                                                   # 0x1
LOGID_ECU_CPU_EVENT_VAL_RTI = (0x0)                                            # 0
LOGID_ECU_CPU_EVENT_VAL_IRQ = (0x1)                                            # 0x1
LOGID_ECU_CPU_EVENT_VAL_XIRQ = (0x2)                                           # 0x2
LOGID_ECU_CPU_EVENT_VAL_SWI = (0x3)                                            # 0x3
LOGID_ECU_CPU_EVENT_VAL_IOP = (0x4)                                            # 0x4
LOGID_ECU_CPU_EVENT_VAL_COP = (0x5)                                            # 0x5
LOGID_ECU_CPU_EVENT_VAL_CMF = (0x6)                                            # 0x6
LOGID_ECU_CPU_EVENT_VAL_RESET = (0x7)                                          # 0x7
LOGID_ECU_CPU_EVENT_VAL_OC5F = (0x8)                                           # 0x8
LOGID_ECU_CPU_EVENT_VAL_OC4F = (0x9)                                           # 0x9
LOGID_ECU_CPU_EVENT_VAL_OC3F = (0xA)                                           # 0xa
LOGID_ECU_CPU_EVENT_VAL_IC3 = (0xB)                                            # 0xb
LOGID_ECU_T1_OFLO_TYPE_TS = ((LOGID_ECU_BASE) + 0x02)                          # ((LOGID_ECU_BASE) + 0x02)
LOGID_ECU_T1_OFLO_DLEN = 2                                                     # 0x2
LOGID_ECU_L4000_EVENT_TYPE_U8 = ((LOGID_ECU_BASE) + 0x08)                      # ((LOGID_ECU_BASE) + 0x08)
LOGID_ECU_L4000_EVENT_DLEN = 1                                                 # 0x1
LOGID_ECU_T1_HOFLO_TYPE_TS = ((LOGID_ECU_BASE) + 0x0E)                      # ((LOGID_ECU_BASE) + 0x0E)
LOGID_ECU_T1_HOFLO_TYPE_DLEN = 2                                            # 0x2
LOGID_ECU_F_INJ_ON_TYPE_PTS = ((LOGID_ECU_BASE) + 0x10)                         # ((LOGID_ECU_BASE) + 0x10)
LOGID_ECU_F_INJ_ON_DLEN = 2                                                    # 0x2
LOGID_ECU_F_INJ_DUR_TYPE_U16 = ((LOGID_ECU_BASE) + 0x12)                       # ((LOGID_ECU_BASE) + 0x12)
LOGID_ECU_F_INJ_DUR_DLEN = 2                                                   # 0x2
LOGID_ECU_R_INJ_ON_TYPE_PTS = ((LOGID_ECU_BASE) + 0x14)                         # ((LOGID_ECU_BASE) + 0x14)
LOGID_ECU_R_INJ_ON_DLEN = 2                                                    # 0x2
LOGID_ECU_R_INJ_DUR_TYPE_U16 = ((LOGID_ECU_BASE) + 0x16)                       # ((LOGID_ECU_BASE) + 0x16)
LOGID_ECU_R_INJ_DUR_DLEN = 2                                                   # 0x2
LOGID_ECU_F_COIL_ON_TYPE_PTS = ((LOGID_ECU_BASE) + 0x20)                        # ((LOGID_ECU_BASE) + 0x20)
LOGID_ECU_F_COIL_ON_DLEN = 2                                                   # 0x2
LOGID_ECU_F_COIL_OFF_TYPE_PTS = ((LOGID_ECU_BASE) + 0x22)                       # ((LOGID_ECU_BASE) + 0x22)
LOGID_ECU_F_COIL_OFF_DLEN = 2                                                  # 0x2
LOGID_ECU_R_COIL_ON_TYPE_PTS = ((LOGID_ECU_BASE) + 0x24)                        # ((LOGID_ECU_BASE) + 0x24)
LOGID_ECU_R_COIL_ON_DLEN = 2                                                   # 0x2
LOGID_ECU_R_COIL_OFF_TYPE_PTS = ((LOGID_ECU_BASE) + 0x26)                       # ((LOGID_ECU_BASE) + 0x26)
LOGID_ECU_R_COIL_OFF_DLEN = 2                                                  # 0x2
LOGID_ECU_F_COIL_MAN_ON_TYPE_PTS = ((LOGID_ECU_BASE) + 0x28)                    # ((LOGID_ECU_BASE) + 0x28)
LOGID_ECU_F_COIL_MAN_ON_DLEN = 2                                               # 0x2
LOGID_ECU_F_COIL_MAN_OFF_TYPE_PTS = ((LOGID_ECU_BASE) + 0x2A)                   # ((LOGID_ECU_BASE) + 0x2A)
LOGID_ECU_F_COIL_MAN_OFF_DLEN = 2                                              # 0x2
LOGID_ECU_R_COIL_MAN_ON_TYPE_PTS = ((LOGID_ECU_BASE) + 0x2C)                    # ((LOGID_ECU_BASE) + 0x2C)
LOGID_ECU_R_COIL_MAN_ON_DLEN = 2                                               # 0x2
LOGID_ECU_R_COIL_MAN_OFF_TYPE_PTS = ((LOGID_ECU_BASE) + 0x2E)                   # ((LOGID_ECU_BASE) + 0x2E)
LOGID_ECU_R_COIL_MAN_OFF_DLEN = 2                                              # 0x2
LOGID_ECU_F_IGN_DLY_TYPE_0P8 = ((LOGID_ECU_BASE) + 0x30)                       # ((LOGID_ECU_BASE) + 0x30)
LOGID_ECU_F_IGN_DLY_DLEN = 1                                                   # 0x1
LOGID_ECU_R_IGN_DLY_TYPE_0P8 = ((LOGID_ECU_BASE) + 0x32)                       # ((LOGID_ECU_BASE) + 0x32)
LOGID_ECU_R_IGN_DLY_DLEN = 1                                                   # 0x1
LOGID_ECU_5MILLISEC_EVENT_TYPE_V = ((LOGID_ECU_BASE) + 0x38)                   # ((LOGID_ECU_BASE) + 0x38)
LOGID_ECU_5MILLISEC_EVENT_DLEN = 1                                             # 0x1
LOGID_ECU_CRANK_P6_MAX_TYPE_V = ((LOGID_ECU_BASE) + 0x39)                      # ((LOGID_ECU_BASE) + 0x39)
LOGID_ECU_CRANK_P6_MAX_DLEN = 1                                                # 0x1
LOGID_ECU_FUEL_PUMP_TYPE_B = ((LOGID_ECU_BASE) + 0x3A)                         # ((LOGID_ECU_BASE) + 0x3A)
LOGID_ECU_FUEL_PUMP_DLEN = 1                                                   # 0x1
LOGID_ECU_ECU_ERROR_L000C_TYPE_U8 = ((LOGID_ECU_BASE) + 0x40)                  # ((LOGID_ECU_BASE) + 0x40)
LOGID_ECU_ECU_ERROR_L000C_DLEN = 1                                             # 0x1
LOGID_ECU_ECU_ERROR_L000D_TYPE_U8 = ((LOGID_ECU_BASE) + 0x41)                  # ((LOGID_ECU_BASE) + 0x41)
LOGID_ECU_ECU_ERROR_L000D_DLEN = 1                                             # 0x1
LOGID_ECU_ECU_ERROR_L000E_TYPE_U8 = ((LOGID_ECU_BASE) + 0x42)                  # ((LOGID_ECU_BASE) + 0x42)
LOGID_ECU_ECU_ERROR_L000E_DLEN = 1                                             # 0x1
LOGID_ECU_ECU_ERROR_L000F_TYPE_U8 = ((LOGID_ECU_BASE) + 0x43)                  # ((LOGID_ECU_BASE) + 0x43)
LOGID_ECU_ECU_ERROR_L000F_DLEN = 1                                             # 0x1
LOGID_ECU_RAW_VTA_TYPE_U16 = ((LOGID_ECU_BASE) + 0x50)                         # ((LOGID_ECU_BASE) + 0x50)
LOGID_ECU_RAW_VTA_DLEN = 2                                                     # 0x2
LOGID_ECU_RAW_MAP_TYPE_U8 = ((LOGID_ECU_BASE) + 0x52)                          # ((LOGID_ECU_BASE) + 0x52)
LOGID_ECU_RAW_MAP_DLEN = 1                                                     # 0x1
LOGID_ECU_RAW_AAP_TYPE_U8 = ((LOGID_ECU_BASE) + 0x53)                          # ((LOGID_ECU_BASE) + 0x53)
LOGID_ECU_RAW_AAP_DLEN = 1                                                     # 0x1
LOGID_ECU_RAW_THW_TYPE_U8 = ((LOGID_ECU_BASE) + 0x54)                          # ((LOGID_ECU_BASE) + 0x54)
LOGID_ECU_RAW_THW_DLEN = 1                                                     # 0x1
LOGID_ECU_RAW_THA_TYPE_U8 = ((LOGID_ECU_BASE) + 0x55)                          # ((LOGID_ECU_BASE) + 0x55)
LOGID_ECU_RAW_THA_DLEN = 1                                                     # 0x1
LOGID_ECU_RAW_VM_TYPE_U8 = ((LOGID_ECU_BASE) + 0x56)                           # ((LOGID_ECU_BASE) + 0x56)
LOGID_ECU_RAW_VM_DLEN = 1                                                      # 0x1
LOGID_ECU_PORTG_DB_TYPE_U8 = ((LOGID_ECU_BASE) + 0x57)                         # ((LOGID_ECU_BASE) + 0x57)
LOGID_ECU_PORTG_DB_DLEN = 1                                                    # 0x1
LOGID_ECU_CRANKREF_START_TYPE_TS = ((LOGID_ECU_BASE) + 0x60)                   # ((LOGID_ECU_BASE) + 0x60)
LOGID_ECU_CRANKREF_START_DLEN = 2                                              # 0x2
LOGID_ECU_CRANKREF_ID_TYPE_U8 = ((LOGID_ECU_BASE) + 0x62)                      # ((LOGID_ECU_BASE) + 0x62)
LOGID_ECU_CRANKREF_ID_DLEN = 1                                                 # 0x1
LOGID_ECU_CAM_ERR_TYPE_U8 = ((LOGID_ECU_BASE) + 0x63)                          # ((LOGID_ECU_BASE) + 0x63)
LOGID_ECU_CAM_ERR_DLEN = 1                                                     # 0x1
LOGID_ECU_CAMSHAFT_TYPE_TS = ((LOGID_ECU_BASE) + 0x64)                         # ((LOGID_ECU_BASE) + 0x64)
LOGID_ECU_CAMSHAFT_DLEN = 2                                                    # 0x2
LOGID_ECU_SPRK_X1_TYPE_TS = ((LOGID_ECU_BASE) + 0x70)                          # ((LOGID_ECU_BASE) + 0x70)
LOGID_ECU_SPRK_X1_DLEN = 2                                                     # 0x2
LOGID_ECU_SPRK_X2_TYPE_TS = ((LOGID_ECU_BASE) + 0x72)                          # ((LOGID_ECU_BASE) + 0x72)
LOGID_ECU_SPRK_X2_DLEN = 2                                                     # 0x2
LOGID_ECU_NOSPARK_TYPE_U8 = ((LOGID_ECU_BASE) + 0x74)                          # ((LOGID_ECU_BASE) + 0x74)
LOGID_ECU_NOSPARK_DLEN = 1                                                     # 0x1
LOGID_GEN_EP_LOG_VER_VAL_V0 = (0x00)                                           # 0
LOGID_EP_LOAD_NAME_TYPE_U8 = ((LOGID_EP_BASE) + 0x00)                          # ((LOGID_EP_BASE) + 0x00)
LOGID_EP_LOAD_NAME_DLEN = 1                                                    # 0x1
LOGID_EP_LOAD_ADDR_TYPE_U16 = ((LOGID_EP_BASE) + 0x02)                         # ((LOGID_EP_BASE) + 0x02)
LOGID_EP_LOAD_ADDR_DLEN = 2                                                    # 0x2
LOGID_EP_LOAD_LEN_TYPE_U16 = ((LOGID_EP_BASE) + 0x04)                          # ((LOGID_EP_BASE) + 0x04)
LOGID_EP_LOAD_LEN_DLEN = 2                                                     # 0x2
LOGID_EP_LOAD_ERR_TYPE_U8 = ((LOGID_EP_BASE) + 0x06)                           # ((LOGID_EP_BASE) + 0x06)
LOGID_EP_LOAD_ERR_DLEN = 1                                                     # 0x1
LOGID_EP_LOAD_ERR_VAL_NOERR = 0x00                                             # 0
LOGID_EP_LOAD_ERR_VAL_NOTFOUND = 0x01                                          # 0x1
LOGID_EP_LOAD_ERR_VAL_NONAME = 0x02                                            # 0x2
LOGID_EP_LOAD_ERR_VAL_CKSUMERR = 0x03                                          # 0x3
LOGID_EP_LOAD_ERR_VAL_VERIFYERR = 0x04                                         # 0x4
LOGID_EP_LOAD_ERR_VAL_BADOFFSET = 0x05                                         # 0x5
LOGID_EP_LOAD_ERR_VAL_BADLENGTH = 0x06                                         # 0x6
LOGID_EP_LOAD_ERR_VAL_NODAUGHTERBOARDKEY = 0x07                                # 0x7
LOGID_EP_LOAD_ERR_VAL_NOMEMKEY = 0x08                                          # 0x8
LOGID_EP_LOAD_ERR_VAL_M3FAIL = 0x09                                            # 0x9
LOGID_EP_LOAD_ERR_VAL_MISSINGKEYSTART = 0x0A                                   # 0xa
LOGID_EP_LOAD_ERR_VAL_MISSINGKEYLENGTH = 0x0B                                  # 0xb
LOGID_EP_LOAD_ERR_VAL_MISSINGKEYM3 = 0x0C                                      # 0xc
LOGID_EP_LOAD_ERR_VAL_BADM3BSONTYPE = 0x0D                                     # 0xd
LOGID_EP_LOAD_ERR_VAL_BADM3VALUE = 0x0E                                        # 0xe
LOGID_EP_LOAD_ERR_VAL_NOBINKEY = 0x0F                                          # 0xf
LOGID_EP_LOAD_ERR_VAL_BADBINLENGTH = 0x10                                      # 0x10
LOGID_EP_LOAD_ERR_VAL_BADBINSUBTYPE = 0x11                                     # 0x11
LOGID_GEN_WP_LOG_VER_VAL_V0 = (0x00)                                           # 0
LOGID_WP_CSECS_TYPE_U8 = ((LOGID_WP_BASE) + 0x01)                              # ((LOGID_WP_BASE) + 0x01)
LOGID_WP_CSECS_DLEN = 1                                                        # 0x1
LOGID_WP_SECS_TYPE_U8 = ((LOGID_WP_BASE) + 0x02)                               # ((LOGID_WP_BASE) + 0x02)
LOGID_WP_SECS_DLEN = 1                                                         # 0x1
LOGID_WP_MINS_TYPE_U8 = ((LOGID_WP_BASE) + 0x03)                               # ((LOGID_WP_BASE) + 0x03)
LOGID_WP_MINS_DLEN = 1                                                         # 0x1
LOGID_WP_HOURS_TYPE_U8 = ((LOGID_WP_BASE) + 0x04)                              # ((LOGID_WP_BASE) + 0x04)
LOGID_WP_HOURS_DLEN = 1                                                        # 0x1
LOGID_WP_DATE_TYPE_U8 = ((LOGID_WP_BASE) + 0x05)                               # ((LOGID_WP_BASE) + 0x05)
LOGID_WP_DATE_DLEN = 1                                                         # 0x1
LOGID_WP_MONTH_TYPE_U8 = ((LOGID_WP_BASE) + 0x06)                              # ((LOGID_WP_BASE) + 0x06)
LOGID_WP_MONTH_DLEN = 1                                                        # 0x1
LOGID_WP_YEAR_TYPE_U8 = ((LOGID_WP_BASE) + 0x07)                               # ((LOGID_WP_BASE) + 0x07)
LOGID_WP_YEAR_DLEN = 1                                                         # 0x1
LOGID_WP_FIXTYPE_TYPE_U8 = ((LOGID_WP_BASE) + 0x08)                            # ((LOGID_WP_BASE) + 0x08)
LOGID_WP_FIXTYPE_DLEN = 1                                                      # 0x1
LOGID_WP_GPS_POSN_TYPE_8B = ((LOGID_WP_BASE) + 0x09)                           # ((LOGID_WP_BASE) + 0x09)
LOGID_WP_GPS_POSN_DLEN = (4+4)                                                 # 0x8
LOGID_WP_GPS_VELO_TYPE_U16 = ((LOGID_WP_BASE) + 0x0A)                          # ((LOGID_WP_BASE) + 0x0A)
LOGID_WP_GPS_VELO_DLEN = 2                                                     # 0x2
LOGID_WP_WR_TIME_TYPE_U16 = ((LOGID_WP_BASE) + 0x0B)                           # ((LOGID_WP_BASE) + 0x0B)
LOGID_WP_WR_TIME_DLEN = 2                                                      # 0x2
LOGID_WP_SYNC_TIME_TYPE_U16 = ((LOGID_WP_BASE) + 0x0C)                         # ((LOGID_WP_BASE) + 0x0C)
LOGID_WP_SYNC_TIME_DLEN = 2                                                    # 0x2
